baseURL = 'https://StupidYoshiaki.github.io/blog/'
languageCode = 'ja-jp'
title = '日記'
theme = 'ananke'
publishDir = '../blog'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "search"
    name = "検索"
    url = "/search/"
    weight = -90
