baseURL = 'https://StupidYoshiaki.github.io/'
languageCode = 'ja-jp'
title = 'ブログ'
theme = 'ananke'
publishDir = '../blog'
relativeURLs = true
uglyURLs = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ホーム"
    url = "/"
    weight = -110
