name: Deploy Hugo Blog to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Hugoテーマのサブモジュールをチェックアウト
          fetch-depth: 0    # 完全な履歴を取得

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --source hugo_blog --destination blog

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog  # Hugoの出力先ディレクトリ
          force_orphan: true   # blogブランチをクリーンアップしてデプロイ
